# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MorphingGUI.ui'
#
# Created: Mon Apr 16 01:08:42 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1044, 868)
        self.loadStart = QtGui.QPushButton(Dialog)
        self.loadStart.setGeometry(QtCore.QRect(60, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.loadStart.setFont(font)
        self.loadStart.setObjectName("loadStart")
        self.loadEnd = QtGui.QPushButton(Dialog)
        self.loadEnd.setGeometry(QtCore.QRect(540, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.loadEnd.setFont(font)
        self.loadEnd.setObjectName("loadEnd")
        self.startImage = QtGui.QGraphicsView(Dialog)
        self.startImage.setGeometry(QtCore.QRect(60, 60, 400, 300))
        self.startImage.setObjectName("startImage")
        self.endImage = QtGui.QGraphicsView(Dialog)
        self.endImage.setGeometry(QtCore.QRect(540, 60, 400, 300))
        self.endImage.setObjectName("endImage")
        self.checkBox = QtGui.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(430, 380, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.horizontalSlider = QtGui.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(160, 430, 711, 20))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(10)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.startLabel = QtGui.QLabel(Dialog)
        self.startLabel.setGeometry(QtCore.QRect(190, 370, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.startLabel.setFont(font)
        self.startLabel.setObjectName("startLabel")
        self.endLabel = QtGui.QLabel(Dialog)
        self.endLabel.setGeometry(QtCore.QRect(670, 370, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.endLabel.setFont(font)
        self.endLabel.setObjectName("endLabel")
        self.alphaLabel = QtGui.QLabel(Dialog)
        self.alphaLabel.setGeometry(QtCore.QRect(100, 430, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.alphaLabel.setFont(font)
        self.alphaLabel.setObjectName("alphaLabel")
        self.alpha1Label = QtGui.QLabel(Dialog)
        self.alpha1Label.setGeometry(QtCore.QRect(850, 450, 21, 17))
        self.alpha1Label.setObjectName("alpha1Label")
        self.alpha0Label = QtGui.QLabel(Dialog)
        self.alpha0Label.setGeometry(QtCore.QRect(160, 450, 21, 17))
        self.alpha0Label.setObjectName("alpha0Label")
        self.blendImage = QtGui.QGraphicsView(Dialog)
        self.blendImage.setGeometry(QtCore.QRect(320, 470, 400, 300))
        self.blendImage.setObjectName("blendImage")
        self.blendLabel = QtGui.QLabel(Dialog)
        self.blendLabel.setGeometry(QtCore.QRect(450, 790, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.blendLabel.setFont(font)
        self.blendLabel.setObjectName("blendLabel")
        self.blendBtn = QtGui.QPushButton(Dialog)
        self.blendBtn.setGeometry(QtCore.QRect(430, 820, 171, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.blendBtn.setFont(font)
        self.blendBtn.setObjectName("blendBtn")
        self.alphaTextBox = QtGui.QLineEdit(Dialog)
        self.alphaTextBox.setGeometry(QtCore.QRect(910, 420, 51, 31))
        self.alphaTextBox.setObjectName("alphaTextBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.loadStart.setText(QtGui.QApplication.translate("Dialog", "Load Starting Image ...", None, QtGui.QApplication.UnicodeUTF8))
        self.loadEnd.setText(QtGui.QApplication.translate("Dialog", "Load Ending Image ...", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog", "Show Triangles", None, QtGui.QApplication.UnicodeUTF8))
        self.startLabel.setText(QtGui.QApplication.translate("Dialog", "Starting Image", None, QtGui.QApplication.UnicodeUTF8))
        self.endLabel.setText(QtGui.QApplication.translate("Dialog", "Ending Image", None, QtGui.QApplication.UnicodeUTF8))
        self.alphaLabel.setText(QtGui.QApplication.translate("Dialog", "Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.alpha1Label.setText(QtGui.QApplication.translate("Dialog", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.alpha0Label.setText(QtGui.QApplication.translate("Dialog", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.blendLabel.setText(QtGui.QApplication.translate("Dialog", "Blending Result", None, QtGui.QApplication.UnicodeUTF8))
        self.blendBtn.setText(QtGui.QApplication.translate("Dialog", "Blend", None, QtGui.QApplication.UnicodeUTF8))

